const stories = [
 {id:"mystery",title:"रहस्यमयी गाँव",en:"The Mystery Village",genre:["Adventure","Mystery","Fantasy"],desc:"एक छोटे से गाँव में छिपा है ऐसा रहस्य, जो आरव की पूरी दुनिया बदल सकता है।",chapters:12,cover:"https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=900&q=85",feature:true},
 {id:"city",title:"शहर का रहस्य",en:"Secrets of the City",genre:["Mystery","Thriller"],desc:"एक अनजान संदेश, एक पुरानी इमारत और सवालों से भरी रात।",chapters:10,cover:"https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=85"},
 {id:"lastletter",title:"अधूरी मोहब्बत",en:"The Last Letter",genre:["Romance","Drama"],desc:"कुछ बातें खतों में रह जाती हैं और कुछ दिल में।",chapters:8,cover:"https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=900&q=85"},
 {id:"jungle",title:"जंगल का दोस्त",en:"A Friend in the Forest",genre:["Adventure","Kids"],desc:"एक बच्चे और जंगल के रहस्यमयी दोस्त की प्यारी कहानी।",chapters:8,cover:"https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=900&q=85"},
 {id:"time",title:"समय का चक्र",en:"The Time Loop",genre:["Sci-Fi","Thriller"],desc:"जब घड़ी रुकती है, तब समय का असली खेल शुरू होता है।",chapters:10,cover:"https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=900&q=85"},
 {id:"gaon",title:"गाँव की बेटी",en:"Daughter of the Village",genre:["Drama","Social"],desc:"हिम्मत, परिवार और अपने सपनों को पाने की कहानी।",chapters:7,cover:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85"}
];
const comics=[
 {title:"वीर और जादुई पेड़",cover:"https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=900&q=85",desc:"वीर को जंगल में मिलता है एक अनोखा दोस्त।"},
 {title:"छोटे जासूस",cover:"https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=85",desc:"दो दोस्तों की मजेदार जासूसी।"},
 {title:"जादुई दुनिया",cover:"https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=900&q=85",desc:"एक दरवाज़ा, दूसरी दुनिया।"},
 {title:"रोबोट की दुनिया",cover:"https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=85",desc:"भविष्य की एक रंगीन कहानी।"}
];
const $=s=>document.querySelector(s);
const path=location.pathname.toLowerCase();
const page=path.endsWith("stories.html")?"stories":path.endsWith("chapter.html")?"chapter":path.endsWith("comic.html")?"comic":"home";
function header(){return `<header class="topbar"><div class="container nav"><a class="brand" href="index.html"><span class="brand-mark">📖</span><span><strong>AJ StoryBooks</strong><small>Stories · Novels · Comics</small></span></a><nav class="navlinks" id="navlinks"><a class="${page==="home"?"active":""}" href="index.html">Home</a><a class="${page==="stories"||page==="chapter"?"active":""}" href="stories.html">Stories</a><a class="${page==="comic"?"active":""}" href="comic.html">Comics</a><a href="#about">About</a></nav><div class="navtools"><input id="navSearch" class="search" placeholder="Search stories…"><button class="iconbtn" id="themeBtn" aria-label="Toggle theme">☾</button><button class="iconbtn menu-toggle" id="menuBtn" aria-label="Open menu">☰</button></div></div></header>`}
function footer(){return `<footer id="about"><div class="container footer-inner"><div><strong>📖 AJ StoryBooks</strong><br>कहानियों की एक नई दुनिया।</div><div>© 2026 AJ StoryBooks. All stories belong to their respective authors.</div><div><a href="stories.html">Stories</a>　·　<a href="comic.html">Comics</a>　·　<a href="#about">About</a></div></div></footer><div class="toast" id="toast"></div>`}
function tags(arr){return `<div class="tag-row">${arr.map((x,i)=>`<span class="tag ${i%3===1?"purple":i%3===2?"green":""}">${x}</span>`).join("")}</div>`}
function storyCard(s){return `<article class="story-card" data-title="${(s.title+" "+s.en+" "+s.genre.join(" ")).toLowerCase()}"><a href="chapter.html?id=${s.id}"><img class="cover" src="${s.cover}" alt="${s.title}" loading="lazy"></a><div class="story-info">${tags(s.genre)}<h3>${s.title}</h3><p>${s.desc}</p><div class="card-bottom"><span>▤ ${s.chapters} Chapters</span><a class="btn small" href="chapter.html?id=${s.id}">Read More →</a></div></div></article>`}
function comicTiles(){return comics.map((c,i)=>`<a class="comic-tile" href="comic.html?page=${i+1}"><img src="${c.cover}" alt="${c.title}" loading="lazy"><span>${c.title}</span></a>`).join("")}
function home(){let f=stories[0];return `<main class="container"><section class="hero"><div class="hero-copy"><div class="eyebrow">Welcome to your story universe</div><h1>AJ StoryBooks</h1><h2 style="margin:0 0 8px;font-size:25px">कहानियों की एक नई दुनिया</h2><p>असली कहानियाँ, अनोखे किरदार और कल्पना से भरी दुनिया — पढ़िए अपनी अगली पसंदीदा कहानी।</p><a class="btn" href="stories.html">Explore Stories　→</a></div></section><section class="section"><div class="section-head"><div><h2>⭐ Featured Story</h2><p>आज की खास कहानी</p></div><a class="textlink" href="stories.html">View all →</a></div><div class="featured-grid"><article class="feature-card"><img class="cover" src="${f.cover}" alt="${f.title}"><div class="feature-copy"><div class="eyebrow">Editor's pick</div><h3>${f.title}</h3>${tags(f.genre)}<p>${f.desc}</p><a class="btn" href="chapter.html?id=${f.id}">Read Now →</a>　<span class="muted" style="font-size:12px">▤ ${f.chapters} Chapters</span></div></article><div class="quick-list"><a class="quick-card" href="stories.html"><span class="quick-icon">📚</span><span><strong>Novel Stories</strong><small>लंबे उपन्यास पढ़ें</small></span>→</a><a class="quick-card" href="comic.html"><span class="quick-icon">🎨</span><span><strong>Comic Stories</strong><small>कहानी चित्रों के साथ</small></span>→</a><a class="quick-card" href="stories.html"><span class="quick-icon">🖼️</span><span><strong>Photo Stories</strong><small>तस्वीरों में कहानी</small></span>→</a><a class="quick-card" href="stories.html"><span class="quick-icon">🗂️</span><span><strong>All Categories</strong><small>अपनी पसंद चुनें</small></span>→</a></div></div></section><section class="section"><div class="section-head"><div><h2>📚 Latest Stories</h2><p>नई कहानियाँ खोजें</p></div><a class="textlink" href="stories.html">View all →</a></div><div class="story-grid">${stories.slice(0,4).map(storyCard).join("")}</div></section><section class="section"><div class="section-head"><div><h2>🎨 Popular Comics</h2><p>चित्रों के साथ मजेदार कहानियाँ</p></div><a class="textlink" href="comic.html">View all →</a></div><div class="comic-strip">${comicTiles()}</div></section></main>`}
function listing(){return `<div class="page-banner"><div class="container"><h1>Our Stories</h1><p>हर कहानी एक नई दुनिया की शुरुआत है।</p></div></div><main class="container"><div class="listing-tools"><input id="storySearch" placeholder="🔎 कहानी का नाम या genre खोजें…"><select id="sortStories"><option value="default">Sort: Featured first</option><option value="az">Name: A–Z</option><option value="chapters">Most chapters</option></select></div><div class="filters" id="filters">${["All","Adventure","Mystery","Fantasy","Romance","Thriller","Sci-Fi","Kids","Drama"].map((g,i)=>`<button class="filter-btn ${i===0?"active":""}" data-filter="${g}">${g}</button>`).join("")}</div><div class="section-head"><div><h2 id="resultTitle">All Stories</h2><p>अपनी अगली पसंदीदा कहानी चुनें।</p></div><span class="muted" id="resultCount"></span></div><div class="story-grid" id="storyGrid"></div></main>`}
function chapter(){let s=stories.find(x=>x.id===new URLSearchParams(location.search).get("id"))||stories[0];return `<main class="container"><article class="reader-shell"><a class="backlink" href="stories.html">← Back to Stories</a><div class="reader-top"><img src="${s.cover}" alt="${s.title}"><div><h1>${s.title}</h1><p>${s.en} · ${s.chapters} Chapters</p>${tags(s.genre)}</div><div class="reader-controls"><select id="chapterSelect">${Array.from({length:s.chapters},(_,i)=>`<option value="${i+1}">Chapter ${i+1} - ${i===0?"गाँव की रहस्यमयी रात":"कहानी का अगला मोड़"}</option>`).join("")}</select><button class="iconbtn" id="fontDown" style="color:var(--ink);background:var(--bg);border-color:var(--line)">A−</button><button class="iconbtn" id="fontUp" style="color:var(--ink);background:var(--bg);border-color:var(--line)">A+</button></div></div><img class="reader-hero" src="${s.cover}" alt="Story illustration"><div class="progress"><span id="readProgress"></span></div><div class="chapter-text" id="chapterText"><h2 id="chapterTitle">Chapter 1 — गाँव की रहस्यमयी रात</h2><p>रात काफी गहरी हो चुकी थी। सोनपुर गाँव की सँकरी गलियों में सन्नाटा पसरा था। दूर पहाड़ी के पीछे से आती हवा पेड़ों की शाखाओं को ऐसे हिला रही थी, मानो कोई धीरे-धीरे किसी अनकही कहानी के पन्ने पलट रहा हो।</p><p>आरव अपने पुराने घर की खिड़की के पास खड़ा था। तभी उसे गाँव के बीचोंबीच बने पुराने कुएँ की तरफ से एक अजीब-सी नीली रोशनी दिखाई दी। उसने आँखें मलीं, लेकिन रोशनी अब भी वहीं थी।</p><img class="story-illustration" src="${s.cover}" alt="रहस्यमयी गाँव का दृश्य"><p>“इतनी रात को वहाँ कौन हो सकता है?” आरव ने खुद से पूछा। उसके मन में डर भी था और जानने की उत्सुकता भी। उसने अपनी टॉर्च उठाई, जूते पहने और दरवाज़े की कुंडी धीरे से खोली।</p><div class="speech">“आरव… वहाँ मत जाना!” पीछे से उसकी छोटी बहन की आवाज़ आई।</div><p>आरव ठिठक गया। बहन के चेहरे पर घबराहट साफ दिखाई दे रही थी। “तुम्हें उस कुएँ के बारे में कुछ पता है?” उसने पूछा। जवाब देने से पहले ही दूर कहीं घंटी बज उठी — एक बार, फिर दूसरी बार… और तीसरी बार पर पूरा गाँव जैसे जाग गया।</p><p>आरव जानता था कि अब वापस लौटना आसान नहीं होगा। उस रात की शुरुआत एक सवाल से हुई थी, लेकिन सुबह होने तक उसकी ज़िंदगी बदलने वाली थी।</p></div><div class="reader-bottom"><button class="btn secondary" id="prevChapter">← Previous Chapter</button><span class="muted" id="chapterCount">Chapter 1 of ${s.chapters}</span><button class="btn" id="nextChapter">Next Chapter →</button></div></article></main>`}
function comic(){let idx=Math.max(1,Math.min(10,Number(new URLSearchParams(location.search).get("page"))||1));return `<main class="container"><article class="comic-shell"><a class="backlink" href="index.html">← Back to Comics</a><div class="comic-head"><img src="${comics[0].cover}" alt="Comic cover"><div><h1>वीर और जादुई पेड़</h1><p>Adventure · Fantasy · Kids · Illustrated comic</p>${tags(["Adventure","Fantasy","Kids"])}</div><div class="comic-actions"><select id="comicPage">${Array.from({length:10},(_,i)=>`<option value="${i+1}" ${i+1===idx?"selected":""}>Page ${i+1} of 10</option>`).join("")}</select><button class="iconbtn" id="comicPrev" style="color:var(--ink);background:var(--bg);border-color:var(--line)">←</button><button class="iconbtn" id="comicNext" style="color:var(--ink);background:var(--bg);border-color:var(--line)">→</button></div></div><div class="comic-grid"><div class="panel"><img src="https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=900&q=85" alt="घना जंगल"><div class="bubble">वाह! ये पेड़ कितना बड़ा है!</div></div><div class="panel"><img src="https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=900&q=85" alt="जादुई पेड़"><div class="bubble">कहते हैं, इस पेड़ में जादुई शक्ति है…</div></div><div class="panel"><img src="https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=900&q=85" alt="जंगल में रोशनी"><div class="bubble">अरे! इसकी शाखाओं से रोशनी निकल रही है!</div></div><div class="panel"><img src="https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=85" alt="रहस्यमयी रात"><div class="bubble">डरो मत वीर, तुम्हें एक खास काम करना है।</div></div></div><div class="comic-nav"><button class="btn secondary" id="comicPrev2">← Previous Page</button><span class="muted" id="comicCount">Page ${idx} of 10</span><button class="btn" id="comicNext2">Next Page →</button></div></article></main>`}
function showToast(msg){let t=$("#toast");if(!t)return;t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
$("#app").innerHTML=header()+(page==="stories"?listing():page==="chapter"?chapter():page==="comic"?comic():home())+footer();
const savedTheme=localStorage.getItem("aj-theme");if(savedTheme==="dark")document.documentElement.dataset.theme="dark";
$("#themeBtn").textContent=document.documentElement.dataset.theme==="dark"?"☀":"☾";
$("#themeBtn").addEventListener("click",()=>{let dark=document.documentElement.dataset.theme!=="dark";document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("aj-theme",dark?"dark":"light");$("#themeBtn").textContent=dark?"☀":"☾"});
$("#menuBtn").addEventListener("click",()=>$("#navlinks").classList.toggle("open"));
$("#navSearch").addEventListener("keydown",e=>{if(e.key==="Enter")location.href="stories.html?q="+encodeURIComponent(e.target.value)});
if(page==="stories"){
 let filter="All";const search=$("#storySearch");search.value=new URLSearchParams(location.search).get("q")||"";
 function render(){let q=search.value.toLowerCase().trim();let arr=stories.filter(s=>(filter==="All"||s.genre.includes(filter))&&(`${s.title} ${s.en} ${s.desc} ${s.genre.join(" ")}`).toLowerCase().includes(q));let sort=$("#sortStories").value;if(sort==="az")arr.sort((a,b)=>a.title.localeCompare(b.title));if(sort==="chapters")arr.sort((a,b)=>b.chapters-a.chapters);$("#storyGrid").innerHTML=arr.length?arr.map(storyCard).join(""):`<div class="empty">कोई कहानी नहीं मिली। दूसरा नाम या category खोजें।</div>`;$("#resultCount").textContent=`${arr.length} stories`;$("#resultTitle").textContent=filter==="All"?"All Stories":filter+" Stories";}
 $("#filters").addEventListener("click",e=>{let b=e.target.closest("button[data-filter]");if(!b)return;filter=b.dataset.filter;document.querySelectorAll(".filter-btn").forEach(x=>x.classList.toggle("active",x===b));render()});search.addEventListener("input",render);$("#sortStories").addEventListener("change",render);render();
}
if(page==="chapter"){let s=stories.find(x=>x.id===new URLSearchParams(location.search).get("id"))||stories[0],n=1;function update(){ $("#chapterTitle").textContent=`Chapter ${n} — ${n===1?"गाँव की रहस्यमयी रात":"कहानी का अगला मोड़"}`;$("#chapterCount").textContent=`Chapter ${n} of ${s.chapters}`;$("#chapterSelect").value=n;$("#readProgress").style.width=(n/s.chapters*100)+"%";$("#prevChapter").disabled=n===1;$("#nextChapter").textContent=n===s.chapters?"Start Again ↻":"Next Chapter →";}$("#chapterSelect").addEventListener("change",e=>{n=Number(e.target.value);update()});$("#nextChapter").addEventListener("click",()=>{n=n===s.chapters?1:n+1;update();window.scrollTo({top:0,behavior:"smooth"})});$("#prevChapter").addEventListener("click",()=>{n=Math.max(1,n-1);update()});$("#fontUp").addEventListener("click",()=>{$("#chapterText").style.fontSize=(parseFloat(getComputedStyle($("#chapterText")).fontSize)+1)+"px"});$("#fontDown").addEventListener("click",()=>{$("#chapterText").style.fontSize=Math.max(13,parseFloat(getComputedStyle($("#chapterText")).fontSize)-1)+"px"});update();}
if(page==="comic"){let n=Math.max(1,Math.min(10,Number(new URLSearchParams(location.search).get("page"))||1));function update(){ $("#comicPage").value=n;$("#comicCount").textContent=`Page ${n} of 10`;$("#comicPrev").disabled=$("#comicPrev2").disabled=n===1;$("#comicNext").textContent=$("#comicNext2").textContent=n===10?"Start Again ↻":"Next Page →";}function move(d){n=n+d;if(n>10)n=1;if(n<1)n=10;update();history.replaceState(null,"","comic.html?page="+n)}$("#comicPrev").addEventListener("click",()=>move(-1));$("#comicPrev2").addEventListener("click",()=>move(-1));$("#comicNext").addEventListener("click",()=>move(1));$("#comicNext2").addEventListener("click",()=>move(1));$("#comicPage").addEventListener("change",e=>{n=Number(e.target.value);update();history.replaceState(null,"","comic.html?page="+n)});update();}
